#define LEFT_FRONT_WHEELS_PORT 1
#define RIGHT_FRONT_WHEELS_PORT 10
#define LEFT_BACK_WHEELS_PORT 11
#define RIGHT_BACK_WHEELS_PORT 20
#define SWEEPER_PORT 7
#define ELEVATOR_PORT 4
#define MOTOR_MAX_SPEED 100 // The motor has the 36 Gearset
